CC=g++
CFLAGS=-Wall -std=c++11

build:
	$(CC) $(CFLAGS) bani.cpp -o bani
	$(CC) $(CFLAGS) gard.cpp -o gard
	$(CC) $(CFLAGS) bomboane.cpp -o bomboane
	$(CC) $(CFLAGS) sala.cpp -o sala

run-p1:
	./bani

run-p2:
	./gard

run-p3:
	./bomboane

run-p4:
	./sala

clean:
	rm -f bani gard bomboane sala
